install.packages("shiny", repos='https://cran.rstudio.com/')
install.packages("ggvis", repos='https://cran.rstudio.com/')
install.packages("shinydashboard", repos='https://cran.rstudio.com/')
install.packages("shinyBS", repos='https://cran.rstudio.com/')
install.packages("reshape2", repos='https://cran.rstudio.com/')
install.packages("ggplot2", repos='https://cran.rstudio.com/')
install.packages("gridExtra", repos='https://cran.rstudio.com/')
install.packages("ghit", repos='https://cran.rstudio.com/')
#ghit::install_github("elenakhusainova/EPI/EPIpackage")
