install.packages("ggvis", repos='https://cran.rstudio.com/')
install.packages("shinydashboard", repos='https://cran.rstudio.com/')
install.packages("shinyBS", repos='https://cran.rstudio.com/')
install.packages("reshape2", repos='https://cran.rstudio.com/')
install.packages("ggplot2", repos='https://cran.rstudio.com/')
install.packages("gridExtra", repos='https://cran.rstudio.com/')
install.packages("DT", repos='https://cran.rstudio.com/')
#install.packages("bigmemory", repos="http://cran.us.r-project.org")
#install.packages("foreach", repos="http://cran.us.r-project.org")
#install.packages("iterators", repos="http://cran.us.r-project.org")
#install.packages("doMC", repos="http://cran.us.r-project.org")
#install.packages("doSNOW", repos="http://cran.us.r-project.org")
#install.packages("itertools", repos="http://cran.us.r-project.org")
devtools::install_github("elenakhusainova/EPI_Rpackage")
